export const SET_GANTT_DATA = 'SET_GANTT_DATA'
export const SET_HEADER_HEIGHT = 'SET_HEADER_HEIGHT'
export const SET_TABLE_TREE = 'SET_TABLE_TREE'
export const TOGGLE_TABLE_TREE_ROW = 'TOGGLE_TABLE_TREE_ROW'